apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: vishwaspaivpipelinesjavascriptdocker 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: vishwaspaivpipelinesjavascriptdocker 
    spec:
      containers:
        - name: vishwaspaivpipelinesjavascriptdocker 
          image: mycontainerregistryvp.azurecr.io/vishwaspaivpipelinesjavascriptdocker
          ports:
          - containerPort: 8080